version: '3.7'
services:
  mylims_backend:
    build: .
    depends_on:
      - mylims_db
    ports:
      - 4000:4000
    environment:
      DB_USER: root
      DB_PWD: example
      DB_HOST: mylims_db
      FILESYSTEM_HOST: mylims_filesystem
      FILESYSTEM_PORT: 5000
    networks:
      - mylims
      - local

  mylims_db:
    image: mongo:4.2.5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - local

networks:
  mylims:
    external:
      name: mylims
  local:
