import { gql } from 'apollo-server-fastify';

export const kindSchema = gql`
  type Kind {
    _id: String! # it's the same generated by MongoDB
    name: String!
    path: [String!]
    description: String
    schema: JSON
  }

  input KindInput {
    name: String!
    path: [String!]
    description: String
    schema: JSON
  }

  extend type Query {
    # search kind by id
    kind(_id: String!): Kind

    # search kind by name
    kindByName(name: String!): [Kind]
  }

  extend type Mutation {
    createKind(kind: KindInput!): Kind
    updateKind(
      _id: String!
      name: String
      path: [String!]
      description: String
      schema: JSON
    ): Kind
  }
`;
