import { gql } from 'apollo-server-fastify';

export const kindSchema = gql`
  type Kind {
    _id: String! # it's the same generated by MongoDB
    name: String!
    description: String
    schema: JSON
  }

  extend type Query {
    # search kind by id
    kind(_id: String!): Kind

    # search kind by name
    kindByName(name: String!): [Kind]
  }
`;
