import { gql } from 'apollo-server-fastify';

export const measurementSchema = gql`
  type Measurement {
    _id: String! # it's the same generated by MongoDB
    sample: String
    title: String!
    description: String
    status: [Status!]
    startTime: String
    endTime: String
    content: JSON
    components: [Component!]
  }

  input MeasurementInput {
    title: String!
    description: String
    status: [StatusInput!]
    startTime: String
    endTime: String
    content: JSON
  }

  extend type Query {
    # search measurement by ids
    measurement(_id: String!): Measurement

    # general search
    measurementByTitle(title: String!): [Measurement!]
  }

  extend type Mutation {
    createMeasurement(measurement: MeasurementInput!): Measurement
    updateMeasurement(
      _id: String!
      title: String
      description: String
      status: [StatusInput!]
      startTime: String
      endTime: String
      content: JSON
    ): Measurement
    appendMeasurementComponent(
      componentId: String!
      measurementId: String!
    ): Component
  }
`;
