import { gql } from 'apollo-server-fastify';

export const componentSchema = gql`
  type Component {
    _id: String! # it's the same generated by MongoDB
    kind: Kind!
    content: JSON
    input: [Component!]
    output: [Component!]
  }

  input ComponentInput {
    kind: String!
    content: JSON
  }

  extend type Query {
    # search component by id
    component(_id: String!): Component
  }

  extend type Mutation {
    createComponent(component: ComponentInput!): Component
    updateComponent(_id: String!, kind: String, content: JSON): Component

    appendComponentInput(parentId: String!, childId: String!): Experiment
    appendComponentOutput(parentId: String!, childId: String!): Experiment
    removeComponentInput(parentId: String!, childId: String!): Experiment
    removeComponentOutput(parentId: String!, childId: String!): Experiment
  }
`;
